version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "DB_DATABASE=roomservice"
      - "DB_USERNAME=roomservice"
      - "DB_PASSWORD=secret"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mariadb:10.11-jammy
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=roomservice"
      - "MYSQL_USER=roomservice"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
